/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// Status : Статус квартиры
type Status string

// List of Status
const (
	CREATED       Status = "created"
	APPROVED      Status = "approved"
	DECLINED      Status = "declined"
	ON_MODERATION Status = "on moderation"
)
