/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type RegisterBody struct {
	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	UserType UserType `json:"user_type,omitempty"`
}
