/*
 * Тестовое задание для отбора на Backend Bootcamp
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package middlewre

import (
	"log/slog"
	"net/http"
	"time"
)

type Logger struct {
	log *slog.Logger
}

func NewLogger(log *slog.Logger) *Logger {
	return &Logger{
		log: log,
	}
}

func (l *Logger) LogRequest(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		logger := l.log.With(
			slog.String("method", r.Method),
			slog.String("path", r.URL.Path),
			slog.String("remote_addr", r.RemoteAddr),
			slog.String("user_agent", r.UserAgent()),
			slog.String("request_id", r.Context().Value(CtxKeyRequestID).(string)),
		)

		logger.Info("request started")

		start := time.Now()
		rw := &responseWriter{w, http.StatusOK}

		next.ServeHTTP(rw, r)

		logger.Info("request completed with",
			slog.Int("status", rw.code),
			slog.String("duration", time.Since(start).String()),
		)
	})
}
