package http

/*
*
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* API version: 1.0.0
* Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

import (
	"github.com/gorilla/mux"
	"houseService/internal/handler/http/middlewre"
	"log/slog"
)

func NewRouter(log *slog.Logger) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	router.Use(middlewre.SetRequestId)

	logger := middlewre.NewLogger(log)
	router.Use(logger.LogRequest)

	return router
}
